<!-- Begin
residingcity = new Array(
new Array(
new Array("--City--", ""),
new Array("Port Blair", "Port Blair"),
new Array("Andaman Nicobar", "Andaman Nicobar")
),

new Array(
new Array("--City--", ""),
new Array("Hyderabad", "Hyderabad"),
new Array("Adilabad", "Adilabad"),
new Array("Anantapur", "Anantapur"),
new Array("Chittoor", "Chittoor"),
new Array("Cuddapah", "Cuddapah"),
new Array("Godavari", "Godavari"),
new Array("Guntur", "Guntur"),
new Array("Karimnagar", "Karimnagar"),
new Array("Khammam", "Khammam"),
new Array("Krishna", "Krishna"),
new Array("Kurnool", "Kurnool"),
new Array("Mahbubnagar", "Mahbubnagar"),
new Array("Medak", "Medak"),
new Array("Nalgonda", "Nalgonda"),
new Array("Nellore", "Nellore"),
new Array("Nizamabad", "Nizamabad"),
new Array("Prakasam", "Prakasam"),
new Array("Rangareddi", "Rangareddi"),
new Array("Srikakulam", "Srikakulam"),
new Array("Visakhapatnam", "Visakhapatnam"),
new Array("Vizianagaram", "Vizianagaram"),
new Array("Warangal", "Warangal"),
new Array("Vijayawada", "Vijayawada")
),

new Array(
new Array("--City--", ""),
new Array("Itanagar", "Itanagar"),
new Array("Changlang", "Changlang"),
new Array("Dibang Valley", "Dibang Valley"),
new Array("Kameng", "Kameng"),
new Array("Kurung Kumey", "Kurung Kumey"),
new Array("Lohit", "Lohit"),
new Array("Subansiri", "Subansiri"),
new Array("Papum Pare", "Papum Pare"),
new Array("Siang", "Siang"),
new Array("Tawang", "Tawang"),
new Array("Tirap", "Tirap")
),

new Array(
new Array("--City--", ""),
new Array("Guwahati", "Guwahati"),
new Array("Barpeta", "Barpeta"),
new Array("Bongaigaon", "Bongaigaon"),
new Array("Cachar", "Cachar"),
new Array("Darrang", "Darrang"),
new Array("Dhemaji", "Dhemaji"),
new Array("Dhubri", "Dhubri"),
new Array("Dibrugarh", "Dibrugarh"),
new Array("Goalpara", "Goalpara"),
new Array("Golaghat", "Golaghat"),
new Array("Hailakandi", "Hailakandi"),
new Array("Jorhat", "Jorhat"),
new Array("Kamrup", "Kamrup"),
new Array("Karbi Anglong", "Karbi Anglong"),
new Array("Karimganj", "Karimganj"),
new Array("Kokrajhar", "Kokrajhar"),
new Array("Lakhimpur", "Lakhimpur"),
new Array("Marigaon", "Marigaon"),
new Array("Nagaon", "Nagaon"),
new Array("Nalbari", "Nalbari"),
new Array("Sivasagar", "Sivasagar"),
new Array("Sonitpur", "Sonitpur"),
new Array("Tinsukia", "Tinsukia")
),

new Array(
new Array("--City--", ""),
new Array("Patna", "Patna"),
new Array("Araria", "Araria"),
new Array("Aurangabad", "Aurangabad"),
new Array("Banka", "Banka"),
new Array("Begusarai", "Begusarai"),
new Array("Bhagalpur", "Bhagalpur"),
new Array("Bhojpur", "Bhojpur"),
new Array("Buxar", "Buxar"),
new Array("Champaran", "Champaran"),
new Array("Darbhanga", "Darbhanga"),
new Array("Gaya", "Gaya"),
new Array("Gopalganj", "Gopalganj"),
new Array("Jamui", "Jamui"),
new Array("Jehanabad", "Jehanabad"),
new Array("Kaimur (Bhabua)", "Kaimur (Bhabua)"),
new Array("Katihar", "Katihar"),
new Array("Khagaria", "Khagaria"),
new Array("Kishanganj", "Kishanganj"),
new Array("Lakhisarai", "Lakhisarai"),
new Array("Madhepura", "Madhepura"),
new Array("Madhubani", "Madhubani"),
new Array("Munger", "Munger"),
new Array("Muzaffarpur", "Muzaffarpur"),
new Array("Nalanda", "Nalanda"),
new Array("Nawada", "Nawada"),
new Array("Purnia", "Purnia"),
new Array("Rohtas", "Rohtas"),
new Array("Saharsa", "Saharsa"),
new Array("Samastipur", "Samastipur"),
new Array("Saran", "Saran"),
new Array("Sheikhpura", "Sheikhpura"),
new Array("Sheohar", "Sheohar"),
new Array("Sitamarhi", "Sitamarhi"),
new Array("Siwan", "Siwan"),
new Array("Supaul", "Supaul"),
new Array("Vaishali", "Vaishali")
),

new Array(
new Array("--City--", ""),
new Array("Chandigarh", "Chandigarh")
),

new Array(
new Array("--City--", ""),
new Array("Raipur", "Raipur"),
new Array("Bastar", "Bastar"),
new Array("Bilaspur", "Bilaspur"),
new Array("Dantewada", "Dantewada"),
new Array("Dhamtari", "Dhamtari"),
new Array("Durg", "Durg"),
new Array("Janjgir-Champa", "Janjgir-Champa"),
new Array("Jashpur", "Jashpur"),
new Array("Kanker", "Kanker"),
new Array("Kawardha", "Kawardha"),
new Array("Korba", "Korba"),
new Array("Koriya", "Koriya"),
new Array("Mahasamund", "Mahasamund"),
new Array("Raigarh", "Raigarh"),
new Array("Rajnandgaon", "Rajnandgaon"),
new Array("Surguja", "Surguja")
),

new Array(
new Array("--City--", ""),
new Array("Silvassa", "Silvassa"),
new Array("Dadra and Nagar Haveli", "Dadra and Nagar Haveli")
),

new Array(
new Array("--City--", ""),
new Array("Daman", "Daman"),
new Array("Daman and Diu", "Daman and Diu")
),

new Array(
new Array("--City--", ""),
new Array("Delhi", "Delhi")
),

new Array(
new Array("--City--", "0"),
new Array("Panaji", "Panaji"),
new Array("Goa", "Goa")
),

new Array(
new Array("--City--", ""),
new Array("Gandhinagar", "Gandhinagar"),
new Array("Ahmedabad", "Ahmedabad"),
new Array("Amreli", "Amreli"),
new Array("Anand", "Anand"),
new Array("Banas Kantha", "Banas Kantha"),
new Array("Bharuch", "Bharuch"),
new Array("Bhavnagar", "Bhavnagar"),
new Array("Dohad", "Dohad"),
new Array("Jamnagar", "Jamnagar"),
new Array("Junagadh", "Junagadh"),
new Array("Kachchh", "Kachchh"),
new Array("Kheda", "Kheda"),
new Array("Mahesana", "Mahesana"),
new Array("Narmada", "Narmada"),
new Array("Navsari", "Navsari"),
new Array("Baroda", "Baroda"),
new Array("Patan", "Patan"),
new Array("Porbandar", "Porbandar"),
new Array("Rajkot", "Rajkot"),
new Array("Sabarkantha", "Sabarkantha"),
new Array("Surat", "Surat"),
new Array("Surendranagar", "Surendranagar"),
new Array("The Dangs", "The Dangs"),
new Array("Vadodara", "Vadodara"),
new Array("Valsad", "Valsad")
),

new Array(
new Array("--City--", ""),
new Array("Chandigarh", "Chandigarh"),
new Array("Ambala", "Ambala"),
new Array("Bhiwani", "Bhiwani"),
new Array("Faridabad", "Faridabad"),
new Array("Fatehabad", "Fatehabad"),
new Array("Gurgaon", "Gurgaon"),
new Array("Hisar", "Hisar"),
new Array("Jhajjar", "Jhajjar"),
new Array("Jind", "Jind"),
new Array("Kaithal", "Kaithal"),
new Array("Karnal", "Karnal"),
new Array("Kurukshetra", "Kurukshetra"),
new Array("Mahendragarh", "Mahendragarh"),
new Array("Panchkula", "Panchkula"),
new Array("Panipat", "Panipat"),
new Array("Rewari", "Rewari"),
new Array("Rohtak", "Rohtak"),
new Array("Sirsa", "Sirsa"),
new Array("Sonipat", "Sonipat"),
new Array("Yamunanagar", "Yamunanagar")
),

new Array(
new Array("--City--", ""),
new Array("Shimla", "Shimla"),
new Array("Bilaspur", "Bilaspur"),
new Array("Chamba", "Chamba"),
new Array("Hamirpur", "Hamirpur"),
new Array("Kangra", "Kangra"),
new Array("Kinnaur", "Kinnaur"),
new Array("Kullu", "Kullu"),
new Array("Lahaul & Spiti", "Lahaul & Spiti"),
new Array("Mandi", "Mandi"),
new Array("Sirmaur", "Sirmaur"),
new Array("Solan", "Solan"),
new Array("Una", "Una")
),

new Array(
new Array("--City--", ""),
new Array("Jammu", "Jammu"),
new Array("Srinagar", "Srinagar"),
new Array("Anantnag", "Anantnag"),
new Array("Baramulla", "Baramulla"),
new Array("Budgam", "Budgam"),
new Array("Doda", "Doda"),
new Array("Kargil", "Kargil"),
new Array("Kathua", "Kathua"),
new Array("Kupwara", "Kupwara"),
new Array("Leh", "Leh"),
new Array("Poonch", "Poonch"),
new Array("Pulwama", "Pulwama"),
new Array("Rajauri", "Rajauri"),
new Array("Udhampur", "Udhampur")
),

new Array(
new Array("--City--", ""),
new Array("Ranchi", "Ranchi"),
new Array("Bokaro", "Bokaro"),
new Array("Chatra", "Chatra"),
new Array("Deoghar", "Deoghar"),
new Array("Dhanbad", "Dhanbad"),
new Array("Dumka", "Dumka"),
new Array("Garhwa", "Garhwa"),
new Array("Giridih", "Giridih"),
new Array("Godda", "Godda"),
new Array("Gumla", "Gumla"),
new Array("Hazaribag", "Hazaribag"),
new Array("Jamtara", "Jamtara"),
new Array("Koderma", "Koderma"),
new Array("Latehar", "Latehar"),
new Array("Lohardaga", "Lohardaga"),
new Array("Pakur", "Pakur"),
new Array("Palamu", "Palamu"),
new Array("Sahibganj", "Sahibganj"),
new Array("Seraikela", "Seraikela"),
new Array("Simdega", "Simdega"),
new Array("Singhbhum", "Singhbhum")
),

new Array(
new Array("--City--", ""),
new Array("Bangalore", "Bangalore"),
new Array("Bagalkot", "Bagalkot"),
new Array("Belgaum", "Belgaum"),
new Array("Bellary", "Bellary"),
new Array("Bidar", "Bidar"),
new Array("Bijapur", "Bijapur"),
new Array("Chamrajnagar", "Chamrajnagar"),
new Array("Chickmagalur", "Chickmagalur"),
new Array("Chitradurga", "Chitradurga"),
new Array("Davangere", "Davangere"),
new Array("Dharwad", "Dharwad"),
new Array("Gadag", "Gadag"),
new Array("Gulbarga", "Gulbarga"),
new Array("Hassan", "Hassan"),
new Array("Haveri", "Haveri"),
new Array("Uttar Kannada", "Uttar Kannada"),
new Array("Dakshin Kannada", "Dakshin Kannada"),
new Array("Kodagu", "Kodagu"),
new Array("Kolar", "Kolar"),
new Array("Koppal", "Koppal"),
new Array("Mandya", "Mandya"),
new Array("Mysore", "Mysore"),
new Array("Raichur", "Raichur"),
new Array("Shimoga", "Shimoga"),
new Array("Tumkur", "Tumkur"),
new Array("Udupi", "Udupi")
),

new Array(
new Array("--City--", ""),
new Array("Thiruvananthapuram", "248"),
new Array("Alappuzha", "Alappuzha"),
new Array("Ernakulam", "Ernakulam"),
new Array("Idukki", "Idukki"),
new Array("Kannur", "Kannur"),
new Array("Kasargod", "Kasargod"),
new Array("Kollam", "Kollam"),
new Array("Kottayam", "Kottayam"),
new Array("Kozhikode", "Kozhikode"),
new Array("Malappuram", "Malappuram"),
new Array("Palakkad", "Palakkad"),
new Array("Pathanamthitta", "Pathanamthitta"),
new Array("Thrissur", "Thrissur"),
new Array("Wayanad", "Wayanad"),
new Array("Cochin", "Cochin")
),

new Array(
new Array("--City--", ""),
new Array("Kavaratti", "Kavaratti"),
new Array("Lakshadweep", "Lakshadweep")
),

new Array(
new Array("--City--", ""),
new Array("Bhopal", "Bhopal"),
new Array("Anuppur", "Anuppur"),
new Array("Ashoknagar", "Ashoknagar"),
new Array("Balaghat", "Balaghat"),
new Array("Barwani", "Barwan"),
new Array("Betul", "Betul"),
new Array("Bhind", "Bhind"),
new Array("Burhanpur", "Burhanpur"),
new Array("Chhatarpur", "Chhatarpur"),
new Array("Chhindwara", "Chhindwara"),
new Array("Damoh", "Damoh"),
new Array("Datia", "Datia"),
new Array("Dewas", "Dewas"),
new Array("Dhar", "Dhar"),
new Array("Dindori", "Dindori"),
new Array("Guna", "Guna"),
new Array("Gwalior", "Gwalior"),
new Array("Harda", "Harda"),
new Array("Hoshangabad", "Hoshangabad"),
new Array("Indore", "Indore"),
new Array("Jabalpur", "Jabalpur"),
new Array("Jhabua", "Jhabua"),
new Array("Katni", "Katni"),
new Array("Khandwa", "Khandwa"),
new Array("Khargone", "Khargone"),
new Array("Mandla", "Mandla"),
new Array("Mandsaur", "Mandsaur"),
new Array("Morena", "Morena"),
new Array("Narsinghpur", "Narsinghpur"),
new Array("Neemuch", "Neemuch"),
new Array("Panna", "Panna"),
new Array("Raisen", "Raisen"),
new Array("Rajgarh", "Rajgarh"),
new Array("Ratlam", "Ratlam"),
new Array("Rewa", "Rewa"),
new Array("Sagar", "Sagar"),
new Array("Satna", "Satna"),
new Array("Sehore", "Sehore"),
new Array("Seoni", "Seoni"),
new Array("Shahdol", "Shahdol"),
new Array("Shajapur", "Shajapur"),
new Array("Sheopur", "Sheopur"),
new Array("Shivpuri", "Shivpuri"),
new Array("Sidhi", "Sidhi"),
new Array("Tikamgarh", "Tikamgarh"),
new Array("Ujjain", "Ujjain"),
new Array("Umaria", "Umaria"),
new Array("Vidisha", "Vidisha")
),

new Array(
new Array("--City--", ""),
new Array("Mumbai", "Mumbai"),
new Array("Ahmednagar", "Ahmednagar"),
new Array("Akola", "Akola"),
new Array("Amravati", "Amravati"),
new Array("Aurangabad", "Aurangabad"),
new Array("Bandra Suburban", "Bandra Suburban"),
new Array("Beed", "Beed"),
new Array("Bhandara", "Bhandara"),
new Array("Buldhana", "Buldhana"),
new Array("Chandrapur", "Chandrapur"),
new Array("Dhule", "Dhule"),
new Array("Gadchiroli", "Gadchiroli"),
new Array("Gondia", "Gondia"),
new Array("Hingoli", "Hingoli"),
new Array("Jalgaon", "Jalgaon"),
new Array("Jalna", "Jalna"),
new Array("Kolhapur", "Kolhapur"),
new Array("Latur", "Latur"),
new Array("Nagpur", "Nagpur"),
new Array("Nanded", "Nanded"),
new Array("Nandurbar", "Nandurbar"),
new Array("Nashik", "Nashik"),
new Array("Osmanabad", "Osmanabad"),
new Array("Parbhani", "Parbhani"),
new Array("Pune", "Pune"),
new Array("Raigarh", "Raigarh"),
new Array("Ratnagiri", "Ratnagiri"),
new Array("Sangli", "Sangli"),
new Array("Satara", "Satara"),
new Array("Sindhudurg", "Sindhudurg"),
new Array("Solapur", "Solapur"),
new Array("Thane", "Thane"),
new Array("Wardha", "Wardha"),
new Array("Washim", "Washim"),
new Array("Yavatmal", "Yavatmal")
),

new Array(
new Array("--City--", ""),
new Array("Imphal", "Imphal"),
new Array("Bishnupur", "Bishnupur"),
new Array("Chandel", "Chandel"),
new Array("Churachandpur", "Churachandpur"),
new Array("Senapati", "Senapati"),
new Array("Tamenglong", "Tamenglong"),
new Array("Thoubal", "Thoubal"),
new Array("Ukhrul", "Ukhrul")
),


new Array(
new Array("--City--", ""),
new Array("Shillong", "Shillong"),
new Array("Garo Hills", "Garo Hills"),
new Array("Jaintia Hills", "Jaintia Hills"),
new Array("Khasi Hills", "Khasi Hills"),
new Array("Ri Bhoi", "Ri Bhoi")
),

new Array(
new Array("--City--", ""),
new Array("Aizawl", "Aizawl"),
new Array("Champhai", "Champhai"),
new Array("Kolasib", "Kolasib"),
new Array("Lawngtlai", "Lawngtlai"),
new Array("Lunglei", "Lunglei"),
new Array("Mamit", "Mamit"),
new Array("Saiha", "Saiha"),
new Array("Serchhip", "Serchhip")
),

new Array(
new Array("--City--", ""),
new Array("Kohima", "Kohima"),
new Array("Dimapur", "Dimapur"),
new Array("Mokokchung", "Mokokchung"),
new Array("Mon", "Mon"),
new Array("Phek", "Phek"),
new Array("Tuensang", "Tuensang"),
new Array("Wokha", "Wokha"),
new Array("Zunheboto", "Zunheboto")
),

new Array(
new Array("--City--", ""),
new Array("Bhubaneshwar", "Bhubaneshwar"),
new Array("Angul", "Angul"),
new Array("Balangir", "Balangir"),
new Array("Baleswar", "Baleswar"),
new Array("Bargarh", "Bargarh"),
new Array("Bhadrak", "Bhadrak"),
new Array("Boudh", "Boudh"),
new Array("Cuttack", "Cuttack"),
new Array("Debagarh", "Debagarh"),
new Array("Dhenkanal", "Dhenkanal"),
new Array("Gajapati", "Gajapati"),
new Array("Ganjam", "Ganjam"),
new Array("Jagatsinghapur", "Jagatsinghapur"),
new Array("Jajapur", "Jajapur"),
new Array("Jharsuguda", "Jharsuguda"),
new Array("Kalahandi", "Kalahandi"),
new Array("Kandhamal", "Kandhamal"),
new Array("Kendrapara", "Kendrapara"),
new Array("Kendujhar", "Kendujhar"),
new Array("Khordha", "Khordha"),
new Array("Koraput", "Koraput"),
new Array("Malkangiri", "Malkangiri"),
new Array("Mayurbhanj", "Mayurbhanj"),
new Array("Nabarangapur", "Nabarangapur"),
new Array("Nayagarh", "Nayagarh"),
new Array("Nuapada", "Nuapada"),
new Array("Puri", "Puri"),
new Array("Rayagada", "Rayagada"),
new Array("Sambalpur", "Sambalpu"),
new Array("Sonapur", "Sonapur"),
new Array("Sundergarh", "Sundergarh")
),

new Array(
new Array("--City--", ""),
new Array("Pondicherry", "Pondicherry"),
new Array("Karaikal", "Karaikal"),
new Array("Mahe", "Mahe"),
new Array("Yanam", "Yanam")
),

new Array(
new Array("--City--", ""),
new Array("Chandigarh", "Chandigarh"),
new Array("Amritsar", "Amritsar"),
new Array("Bathinda", "Bathinda"),
new Array("Faridkot", "Faridkot"),
new Array("Fatehgarh Sahib", "Fatehgarh Sahib"),
new Array("Firozpur", "Firozpur"),
new Array("Gurdaspur", "Gurdaspur"),
new Array("Hoshiarpur", "Hoshiarpur"),
new Array("Jalandhar", "Jalandhar"),
new Array("Kapurthala", "Kapurthala"),
new Array("Ludhiana", "Ludhiana"),
new Array("Mansa", "Mansa"),
new Array("Moga", "Moga"),
new Array("Muktsar", "Muktsar"),
new Array("Nawanshahr", "Nawanshahr"),
new Array("Patiala", "Patiala"),
new Array("Rupnagar", "Rupnagar"),
new Array("Sangrur", "Sangrur")
),

new Array(
new Array("--City--", ""),
new Array("Jaipur", "Jaipur"),
new Array("Ajmer", "Ajmer"),
new Array("Alwar", "Alwar"),
new Array("Banswara", "Banswara"),
new Array("Baran", "Baran"),
new Array("Barmer", "Barmer"),
new Array("Bharatpur", "Bharatpur"),
new Array("Bhilwara", "Bhilwara"),
new Array("Bikaner", "Bikaner"),
new Array("Bundi", "Bundi"),
new Array("Chittorgarh", "Chittorgarh"),
new Array("Churu", "Churu"),
new Array("Dausa", "Dausa"),
new Array("Dholpur", "Dholpur"),
new Array("Dungarpur", "Dungarpur"),
new Array("Ganganagar", "Ganganagar"),
new Array("Hanumangarh", "Hanumangarh"),
new Array("Jaisalmer", "Jaisalmer"),
new Array("Jalor", "Jalor"),
new Array("Jhalawar", "Jhalawar"),
new Array("Jhunjhunu", "Jhunjhunu"),
new Array("Jodhpur", "Jodhpur"),
new Array("Karauli", "Karauli"),
new Array("Kota", "Kota"),
new Array("Nagaur", "Nagaur"),
new Array("Pali", "Pali"),
new Array("Rajsamand", "Rajsamand"),
new Array("Sawai Madhopur", "Sawai Madhopur"),
new Array("Sikar", "Sikar"),
new Array("Sirohi", "Sirohi"),
new Array("Tonk", "Tonk"),
new Array("Udaipur", "Udaipur")
),

new Array(
new Array("--City--", ""),
new Array("Gangtok", "Gangtok"),
new Array("Sikkim", "Sikkim")
),

new Array(
new Array("--City--", ""),
new Array("Chennai", "Chennai"),
new Array("Coimbatore", "Coimbatore"),
new Array("Cuddalore", "Cuddalore"),
new Array("Dharmapuri", "Dharmapuri"),
new Array("Dindigul", "Dindigul"),
new Array("Erode", "Erode"),
new Array("Kanchipuram", "Kanchipuram"),
new Array("Kanyakumari", "Kanyakumari"),
new Array("Karur", "Karur"),
new Array("Krishnagiri", "Krishnagiri"),
new Array("Madurai", "Madurai"),
new Array("Nagapattinam", "Nagapattinam"),
new Array("Namakkal", "Namakkal"),
new Array("Nilgiris", "Nilgiris"),
new Array("Perambalur", "Perambalur"),
new Array("Pudukkottai", "Pudukkottai"),
new Array("Ramanathapuram", "Ramanathapuram"),
new Array("Salem", "Salem"),
new Array("Sivaganga", "Sivaganga"),
new Array("Thanjavur", "Thanjavur"),
new Array("Theni", "Theni"),
new Array("Thoothukudi", "Thoothukudi"),
new Array("Tiruchirappalli", "Tiruchirappalli"),
new Array("Tirunelveli", "Tirunelveli"),
new Array("Tiruvallur", "Tiruvallur"),
new Array("Tiruvannamalai", "Tiruvannamalai"),
new Array("Tiruvarur", "Tiruvarur"),
new Array("Vellore", "Vellore"),
new Array("Viluppuram", "Viluppuram"),
new Array("Virudhunagar", "Virudhunagar")
),

new Array(
new Array("--City--", ""),
new Array("Agartala", "Agartala"),
new Array("Dhalai", "Dhalai"),
new Array("Tripura", "Tripura")
),

new Array(
new Array("--City--", ""),
new Array("Lucknow", "Lucknow"),
new Array("Agra", "Agra"),
new Array("Aligarh", "Aligarh"),
new Array("Allahabad", "Allahabad"),
new Array("Ambedkar Nagar", "Ambedkar Nagar"),
new Array("Auraiya", "Auraiya"),
new Array("Azamgarh", "Azamgarh"),
new Array("Bagpat", "Bagpat"),
new Array("Bahraich", "Bahraich"),
new Array("Ballia", "Ballia"),
new Array("Balrampur", "Balrampur"),
new Array("Banda", "Banda"),
new Array("Barabanki", "Barabanki"),
new Array("Bareilly", "Bareilly"),
new Array("Basti", "Basti"),
new Array("Bijnor", "Bijnor"),
new Array("Budaun", "Budaun"),
new Array("Bulandshahr", "Bulandshahr"),
new Array("Chandauli", "Chandauli"),
new Array("Chitrakoot", "Chitrakoot"),
new Array("Deoria", "Deoria"),
new Array("Etah", "Etah"),
new Array("Etawah", "Etawah"),
new Array("Faizabad", "Faizabad"),
new Array("Farrukhabad", "Farrukhabad"),
new Array("Fatehpur", "Fatehpur"),
new Array("Firozabad", "Firozabad"),
new Array("Gautam Buddha Nagar", "Gautam Buddha Nagar"),
new Array("Ghaziabad", "Ghaziabad"),
new Array("Ghazipur", "Ghazipur"),
new Array("Gonda", "Gonda"),
new Array("Gorakhpur", "Gorakhpur"),
new Array("Hamirpur", "Hamirpur"),
new Array("Hardoi", "Hardoi"),
new Array("Hathras", "Hathras"),
new Array("Jalaun", "Jalaun"),
new Array("Jaunpur", "Jaunpur"),
new Array("Jhansi", "Jhansi"),
new Array("Jyotiba Phule Nagar", "Jyotiba Phule Nagar"),
new Array("Kannauj", "Kannauj"),
new Array("Kanpur Dehat", "Kanpur Dehat"),
new Array("Kanpur", "Kanpur"),
new Array("Kaushambi", "Kaushambi"),
new Array("Kheri", "Kheri"),
new Array("Kushinagar", "Kushinagar"),
new Array("Lalitpur", "Lalitpur"),
new Array("Maharajganj", "Maharajganj"),
new Array("Mahoba", "Mahoba"),
new Array("Mainpuri", "Mainpuri"),
new Array("Mathura", "Mathura"),
new Array("Mau", "Mau"),
new Array("Meerut", "Meerut"),
new Array("Mirzapur", "Mirzapur"),
new Array("Moradabad", "Moradabad"),
new Array("Muzaffarnagar", "Muzaffarnagar"),
new Array("Noida", "Noida"),
new Array("Pilibhit", "Pilibhit"),
new Array("Pratapgarh", "Pratapgarh"),
new Array("RaeBareli", "RaeBareli"),
new Array("Rampur", "Rampur"),
new Array("Saharanpur", "Saharanpur"),
new Array("Sant Kabir Nagar", "Sant Kabir Nagar"),
new Array("Sant Ravidas Nagar", "Sant Ravidas Nagar"),
new Array("Sahanpur", "Sahanpur"),
new Array("Shrawasti", "Shrawasti"),
new Array("Siddharthnagar", "Siddharthnagar"),
new Array("Sitapur", "Sitapur"),
new Array("Sonbhadra", "Sonbhadra"),
new Array("Sultanpur", "Sultanpur"),
new Array("Unnao", "Unnao"),
new Array("Varanasi", "Varanasi")
),

new Array(
new Array("--City--", ""),
new Array("Dehradun", "Dehradun"),
new Array("Almora", "Almora"),
new Array("Bageshwar", "Bageshwar"),
new Array("Chamoli", "Chamoli"),
new Array("Champawat", "Champawat"),
new Array("Haridwar", "Haridwar"),
new Array("Nainital", "Nainital"),
new Array("Pauri Garhwal", "Pauri Garhwal"),
new Array("Pithoragarh", "Pithoragarh"),
new Array("Rudraprayag", "Rudraprayag"),
new Array("Tehri Garhwal", "Tehri Garhwal"),
new Array("Udham Singh Nagar", "Udham Singh Nagar"),
new Array("Uttarkashi", "Uttarkashi")
),

new Array(
new Array("--City--", ""),
new Array("Kolkata", "Kolkata"),
new Array("24 Parganas", "24 Parganas"),
new Array("Bankura", "Bankura"),
new Array("Bardhaman", "Bardhaman"),
new Array("Birbhum", "Birbhum"),
new Array("Cooch Behar", "Cooch Behar"),
new Array("Darjiling", "Darjiling"),
new Array("Dinajpur", "Dinajpur"),
new Array("Hooghly", "Hooghly"),
new Array("Howrah", "Howrah"),
new Array("Jalpaiguri", "Jalpaiguri"),
new Array("Malda", "Malda"),
new Array("Midnapore", "Midnapore"),
new Array("Murshidabad", "Murshidabad"),
new Array("Nadia", "Nadia"),
new Array("Puruliya", "Puruliya")
),

null,
new Array(
new Array("", "")
)
);
function fillSelectFromArray1(selectCtrl, itemArray, goodPrompt, badPrompt, defaultItem) {
var i, j;
var prompt;
// empty existing items
for (i = selectCtrl.options.length; i >= 0; i--) {
selectCtrl.options[i] = null; 
}
prompt = (itemArray != null) ? goodPrompt : badPrompt;
if (prompt == null) {
j = 0;
}
else {
selectCtrl.options[0] = new Option(prompt);
j = 1;
}
if (itemArray != null) {
// add new items
for (i = 0; i < itemArray.length; i++) {
selectCtrl.options[j] = new Option(itemArray[i][0]);
if (itemArray[i][1] != null) {
selectCtrl.options[j].value = itemArray[i][1]; 
}
j++;
}
// select first item (prompt) for sub list
selectCtrl.options[0].selected = true;
   }
}
//  End -->